name: ModuleTest

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build, lint, and test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check PowerShell Version
        shell: powershell
        run: |
          $PSVersionTable
      
      - name: Run Build
        shell: powershell
        run: |
          .\build.ps1
